/**
 * @whalepod/schema — Drizzle table definitions + zod input schemas.
 *
 * Source of truth: docs/phase-2.md §4.1.
 *
 * All tables map 1:1 to the spec. Migrations are generated by drizzle-kit and
 * committed to `src/db/migrations/`. Never edit migrations after they ship.
 */
import {
  bigint,
  boolean,
  check,
  customType,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

/** Postgres `bytea` mapped to Node `Uint8Array`. */
const bytea = customType<{ data: Uint8Array; driverData: Buffer }>({
  dataType() {
    return 'bytea';
  },
  fromDriver(value) {
    return new Uint8Array(value);
  },
  toDriver(value) {
    return Buffer.from(value);
  },
});

// ─── users ───────────────────────────────────────────────────────────────────
export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tgUserId: bigint('tg_user_id', { mode: 'bigint' }).notNull().unique(),
    tgUsername: text('tg_username'),
    mainWallet: text('main_wallet').notNull(),
    agentAddress: text('agent_address').notNull(),
    agentKeyCt: bytea('agent_key_ct').notNull(),
    agentKeyIv: bytea('agent_key_iv').notNull(),
    agentKeyTag: bytea('agent_key_tag').notNull(),
    agentDekCt: bytea('agent_dek_ct').notNull(),
    approvedMaxFeeTenthsBp: integer('approved_max_fee_tenths_bp').notNull(),
    currentFeeTenthsBp: integer('current_fee_tenths_bp').notNull().default(30),
    equityFloorUsd: numeric('equity_floor_usd', { precision: 18, scale: 2 }).notNull().default('0'),
    killSwitch: boolean('kill_switch').notNull().default(false),
    notifyMuted: boolean('notify_muted').notNull().default(false),
    notifyCompact: boolean('notify_compact').notNull().default(false),
    geofenceCountry: text('geofence_country'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
  },
  (t) => ({
    tgUserIdx: index('users_tg_user_idx').on(t.tgUserId),
    mainWalletIdx: index('users_main_wallet_idx').on(t.mainWallet),
    approvedFeeNonNeg: check(
      'users_approved_max_fee_nonneg',
      sql`${t.approvedMaxFeeTenthsBp} >= 0 AND ${t.approvedMaxFeeTenthsBp} <= 100`,
    ),
    currentFeeNonNeg: check(
      'users_current_fee_nonneg',
      sql`${t.currentFeeTenthsBp} >= 0 AND ${t.currentFeeTenthsBp} <= ${t.approvedMaxFeeTenthsBp}`,
    ),
  }),
);

// ─── whales ──────────────────────────────────────────────────────────────────
export const whales = pgTable(
  'whales',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    address: text('address').notNull().unique(),
    alias: text('alias'),
    isFeatured: boolean('is_featured').notNull().default(false),
    addedBy: uuid('added_by').references(() => users.id, { onDelete: 'set null' }),
    lastFillAt: timestamp('last_fill_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    addressIdx: index('whales_address_idx').on(t.address),
    featuredIdx: index('whales_featured_last_fill_idx').on(t.isFeatured, t.lastFillAt),
  }),
);

// ─── subscriptions ───────────────────────────────────────────────────────────
export const subscriptions = pgTable(
  'subscriptions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    whaleId: uuid('whale_id')
      .notNull()
      .references(() => whales.id),
    maxSizeUsd: numeric('max_size_usd', { precision: 18, scale: 2 }).notNull(),
    maxLeverage: integer('max_leverage').notNull(),
    allowedCoins: text('allowed_coins').array(),
    paused: boolean('paused').notNull().default(false),
    tpBps: integer('tp_bps'),
    slBps: integer('sl_bps'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userWhaleUnique: uniqueIndex('subscriptions_user_whale_unique').on(t.userId, t.whaleId),
    whalePausedIdx: index('subscriptions_whale_paused_idx').on(t.whaleId, t.paused),
    leverageRange: check('subscriptions_leverage_range', sql`${t.maxLeverage} BETWEEN 1 AND 50`),
    maxSizePositive: check('subscriptions_max_size_positive', sql`${t.maxSizeUsd} > 0`),
    // TP/SL offsets are in basis-points-of-entry, 1..9999 (10000 would imply
    // a stop at price 0 for SL — see packages/sdk/src/trigger.ts).
    tpBpsRange: check(
      'subscriptions_tp_bps_range',
      sql`${t.tpBps} IS NULL OR (${t.tpBps} BETWEEN 1 AND 9999)`,
    ),
    slBpsRange: check(
      'subscriptions_sl_bps_range',
      sql`${t.slBps} IS NULL OR (${t.slBps} BETWEEN 1 AND 9999)`,
    ),
  }),
);

// ─── watches ─────────────────────────────────────────────────────────────────
// Zero-trust alert subscriptions: a Telegram user gets a ping on every fill
// from a whale WITHOUT connecting a wallet. Keyed by tg_user_id directly (no
// users FK — watchers usually have no user row yet; that's the whole point).
export const watches = pgTable(
  'watches',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tgUserId: bigint('tg_user_id', { mode: 'bigint' }).notNull(),
    whaleId: uuid('whale_id')
      .notNull()
      .references(() => whales.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tgWhaleUnique: uniqueIndex('watches_tg_whale_unique').on(t.tgUserId, t.whaleId),
    whaleIdx: index('watches_whale_idx').on(t.whaleId),
    tgUserIdx: index('watches_tg_user_idx').on(t.tgUserId),
  }),
);

// ─── fills ───────────────────────────────────────────────────────────────────
export const fills = pgTable(
  'fills',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    hlFillId: text('hl_fill_id').notNull().unique(),
    wallet: text('wallet').notNull(),
    coin: text('coin').notNull(),
    side: text('side').notNull(),
    px: numeric('px', { precision: 38, scale: 8 }).notNull(),
    sz: numeric('sz', { precision: 38, scale: 8 }).notNull(),
    notionalUsd: numeric('notional_usd', { precision: 18, scale: 2 }).notNull(),
    isMirror: boolean('is_mirror').notNull(),
    mirrorOfId: uuid('mirror_of_id'),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    builderFeeTenthsBp: integer('builder_fee_tenths_bp'),
    builderFeeUsd: numeric('builder_fee_usd', { precision: 18, scale: 6 }),
    realizedPnlUsd: numeric('realized_pnl_usd', { precision: 18, scale: 6 }),
    ts: timestamp('ts', { withTimezone: true }).notNull(),
    /** Set by FillReconciler after pulling HL truth into px/realizedPnlUsd/builderFeeUsd.
     *  NULL = row still holds locally-estimated values from submitMirror time. */
    reconciledAt: timestamp('reconciled_at', { withTimezone: true }),
  },
  (t) => ({
    walletTsIdx: index('fills_wallet_ts_idx').on(t.wallet, t.ts),
    userTsIdx: index('fills_user_ts_idx').on(t.userId, t.ts),
    mirrorOfIdx: index('fills_mirror_of_idx').on(t.mirrorOfId),
    reconciledAtIdx: index('fills_reconciled_at_idx').on(t.reconciledAt),
    mirrorOfFk: foreignKey({
      columns: [t.mirrorOfId],
      foreignColumns: [t.id],
      name: 'fills_mirror_of_self_fk',
    }).onDelete('set null'),
    sideCheck: check('fills_side_check', sql`${t.side} IN ('B','S')`),
  }),
);

// ─── referrals ───────────────────────────────────────────────────────────────
export const referrals = pgTable(
  'referrals',
  {
    code: text('code').primaryKey(),
    ownerUserId: uuid('owner_user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    ownerUnique: unique('referrals_owner_user_id_unique').on(t.ownerUserId),
  }),
);

export const referralsAttribution = pgTable('referrals_attribution', {
  referredUserId: uuid('referred_user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  code: text('code')
    .notNull()
    .references(() => referrals.code),
  firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).notNull().defaultNow(),
});

// ─── audit_log ───────────────────────────────────────────────────────────────
export const auditLog = pgTable(
  'audit_log',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    actor: text('actor').notNull(),
    action: text('action').notNull(),
    target: text('target').notNull(),
    beforeJson: jsonb('before_json'),
    afterJson: jsonb('after_json'),
    ts: timestamp('ts', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    tsIdx: index('audit_log_ts_idx').on(t.ts),
    actorTsIdx: index('audit_log_actor_ts_idx').on(t.actor, t.ts),
  }),
);

// ─── kill_switches_global ────────────────────────────────────────────────────
export const killSwitchesGlobal = pgTable(
  'kill_switches_global',
  {
    id: integer('id').primaryKey(),
    enabled: boolean('enabled').notNull().default(false),
    reason: text('reason'),
    setBy: text('set_by'),
    setAt: timestamp('set_at', { withTimezone: true }),
  },
  (t) => ({
    singletonOnly: check('kill_switches_global_singleton', sql`${t.id} = 1`),
  }),
);
