import { HL_SIG_CHAIN_ID } from './constants.js';
import type { Address } from '@whalepod/schema';
import type { HlApproveAgentAction } from './types.js';

export interface BuildApproveAgentInput {
  /** Sub-account agent address (lowercased). Generated by @whalepod/vault. */
  readonly agentAddress: Address;
  /** Human-friendly agent name shown in HL UIs. Server-controlled, NOT user input. */
  readonly agentName: string;
  /** Mainnet or Testnet. Server-pinned, NEVER user-controlled. */
  readonly chain: 'Mainnet' | 'Testnet';
  /** Nonce — current ms timestamp. Caller provides for testability. */
  readonly nonce: number;
}

/**
 * Build the HL `approveAgent` action. The user signs this with their MAIN
 * wallet during onboarding to authorize the freshly-generated agent key.
 *
 * The agent address itself never appears in any withdrawal-capable action:
 * the protocol disallows `withdraw3`/`usdSend`/`spotSend` signatures from
 * agent keys, and our ESLint rules forbid those literal strings from ever
 * appearing in the bot, ws-consumer, sdk, or vault packages.
 */
export function buildApproveAgentAction(input: BuildApproveAgentInput): HlApproveAgentAction {
  return {
    type: 'approveAgent',
    hyperliquidChain: input.chain,
    signatureChainId: HL_SIG_CHAIN_ID,
    agentAddress: input.agentAddress,
    agentName: input.agentName,
    nonce: input.nonce,
  };
}
